// Compatibility palette for the existing Tailwind utilities and literal brand colors.
// Run after introducing new literal colors: node scripts/generate_workspace_theme.cjs
const fs = require("fs");
const path = require("path");
const colors = require("tailwindcss/colors");
const files = [];
function walk(dir) {
  for (const item of fs.readdirSync(dir, {withFileTypes: true})) {
    const file = path.join(dir, item.name);
    if (item.isDirectory()) walk(file);
    else if (/\.(js|jsx)$/.test(file)) files.push(file);
  }
}
walk("src");
const tokens = new Set();
for (const file of files) {
  const text = fs.readFileSync(file, "utf8");
  for (const match of text.matchAll(/(?:(?:hover|focus|focus-visible|disabled|placeholder|sm|md|lg):)*(?:bg|text|border|divide|ring-offset|from|to)-(?:\[#[a-fA-F0-9]{3,8}\]|[a-z]+(?:-\d{2,3})?)(?:\/\d{1,3})?/g)) tokens.add(match[0]);
}
// Include commonly composed neutral utilities as well.
for (const family of ["gray", "slate", "zinc", "neutral", "stone"]) {
  for (const shade of [50,100,200,300,400,500,600,700,800,900,950]) {
    for (const type of ["bg", "text", "border", "divide"]) tokens.add(`${type}-${family}-${shade}`);
  }
}
const groups = new Map();
const escape = value => value.replace(/[^a-zA-Z0-9_-]/g, value => "\\" + value);
for (const token of [...tokens].sort((a,b) => Number(a.includes(":"))-Number(b.includes(":")) || a.localeCompare(b))) {
  const parts = token.split(":");
  const base = parts.pop();
  const match = base.match(/^(bg|text|border|divide|ring-offset|from|to)-(.+?)(?:\/(\d+))?$/);
  if (!match) continue;
  const [,type,name,opacity] = match;
  let hex;
  if (name.startsWith("[#")) hex = name.slice(1,-1);
  else if (name === "white") hex = "#ffffff";
  else if (name === "black") hex = "#000000";
  else {
    const [family,shade] = name.split("-");
    if (!["gray","slate","zinc","neutral","stone","red","orange","amber","yellow","lime","green","emerald","teal","cyan","sky","blue","indigo","violet","purple","fuchsia","pink","rose"].includes(family)) continue;
    hex = colors[family]?.[shade];
  }
  if (!hex || !/^#[a-f0-9]{6}$/i.test(hex)) continue;
  const rgb = [1,3,5].map(i => parseInt(hex.slice(i,i+2),16));
  const light = (Math.max(...rgb)+Math.min(...rgb))/510;
  let target;
  if ((["bg", "ring-offset", "from", "to"].includes(type)) && light > .78) {
    const max = Math.max(...rgb), min = Math.min(...rgb);
    if (max-min > 30) target = rgb.map(v => Math.round(22 + 35*(v-min)/(max-min)));
    else if (name === "white") target = [30,41,59];
    else if (light > .965) target = [15,23,42];
    else if (light > .9) target = [25,35,50];
    else target = [40,50,68];
  } else if (type === "text" && light < .68) {
    const max = Math.max(...rgb), min = Math.min(...rgb);
    target = max-min < 38 ? [light < .22 ? 232 : 186, light < .22 ? 237 : 196, light < .22 ? 243 : 209]
      : rgb.map(v => Math.round(135 + v/255*105));
  } else if ((type === "border" || type === "divide") && light > .65) {
    target = rgb.map(v => Math.round(35+v/255*38));
  }
  if (!target) continue;
  const value = `rgb(${target.join(" ")}${opacity ? " / " + Number(opacity)/100 : ""})`;
  const prop = type === "from" ? "--tw-gradient-from" : type === "to" ? "--tw-gradient-to" : type === "bg" ? "background-color" : type === "text" ? "color" : type === "ring-offset" ? "--tw-ring-offset-color" : "border-color";
  let selector = `:where(:root[data-theme="dark"]) .${escape(token)}`;
  let media = "";
  for (const variant of parts) {
    if (["sm","md","lg"].includes(variant)) media = {sm:640,md:768,lg:1024}[variant];
    else selector += variant === "placeholder" ? "::placeholder" : ":"+variant;
  }
  if (type === "divide") selector += " > :not([hidden]) ~ :not([hidden])";
  const key = [media,parts.length > 0,prop,value].join("|");
  if (!groups.has(key)) groups.set(key,[]);
  groups.get(key).push(selector);
}
let css = `/* Generated by scripts/generate_workspace_theme.cjs. Images, canvas and document embeds are not recolored. */
:root { --workspace-bg: #f8f9fa; --workspace-surface: #ffffff; --workspace-text: #202124; --workspace-border: #dadce0; }
:root[data-theme="dark"] { --workspace-bg: #111827; --workspace-surface: #23272f; --workspace-text: #e8edf3; --workspace-border: #48505e; color-scheme: dark; }
body { background-color: var(--workspace-bg); color: var(--workspace-text); }
:where(:root[data-theme="dark"]) *, :where(:root[data-theme="dark"]) ::before, :where(:root[data-theme="dark"]) ::after { border-color: var(--workspace-border); }
:where(:root[data-theme="dark"]) textarea, :where(:root[data-theme="dark"]) select, :where(:root[data-theme="dark"]) input:not([type="checkbox"]):not([type="radio"]):not([type="range"]):not([type="file"]) { background-color: var(--workspace-surface); color: var(--workspace-text); }
.workspace-theme-toggle { position: fixed; bottom: max(1rem, env(safe-area-inset-bottom)); right: max(1rem, env(safe-area-inset-right)); z-index: 40; display: flex; align-items: center; gap: .5rem; padding: .65rem .85rem; border: 1px solid var(--workspace-border); border-radius: 999px; background: var(--workspace-surface); color: var(--workspace-text); box-shadow: 0 3px 14px rgb(0 0 0 / .18); font-size: .8125rem; font-weight: 600; }
.workspace-theme-toggle:focus-visible { outline: 3px solid #34d399; outline-offset: 3px; }
:root[data-theme="dark"] input, :root[data-theme="dark"] textarea, :root[data-theme="dark"] select { color-scheme: dark; }
:root[data-theme="dark"] input::placeholder, :root[data-theme="dark"] textarea::placeholder { color: #9caabd; }
:root[data-theme="dark"] option { background: #23272f; color: #e8edf3; }
:root[data-theme="dark"] ::selection { background: #285d50; color: #ffffff; }
@media (max-width: 480px) { .workspace-theme-toggle span { display: none; } .workspace-theme-toggle { padding: .75rem; } }
`;
for (const [key,selectors] of groups) {
  const [media,,prop,value] = key.split("|");
  const rule = `${selectors.join(",\n")} { ${prop}: ${value}; }\n`;
  css += media ? `@media (min-width: ${media}px) {\n${rule}}\n` : rule;
}
fs.writeFileSync("src/workspace-theme.css",css);
