/** Run with an external @electric-sql/pglite package path; no application dependency. */
const fs = require('fs');
const assert = require('node:assert/strict');
const { PGlite } = require(process.argv[2] || '@electric-sql/pglite');
(async () => {
  const db = new PGlite();
  const [t, other, s, peer, outsider, A, B, a, b, work] = Array.from({length:10}, (_,i)=>`00000000-0000-0000-0000-${String(i+1).padStart(12,'0')}`);
  const a2 = '00000000-0000-0000-0000-000000000011';
  await db.exec(`CREATE ROLE authenticated; CREATE ROLE anon; CREATE SCHEMA auth;
    CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('test.uid',true),'')::uuid $$;
    GRANT USAGE ON SCHEMA auth TO authenticated, anon;
    CREATE TABLE "userTable" (id uuid PRIMARY KEY, full_name text, role text, account_status text DEFAULT 'active');
    CREATE TABLE "classroomTable" (id uuid PRIMARY KEY, teacher_id uuid, is_archived boolean);
    CREATE TABLE "classroomMembers" (classroom_id uuid, student_id uuid);
    CREATE TABLE "assignmentTable" (id uuid PRIMARY KEY, classroom_id uuid, teacher_id uuid);
    CREATE TABLE "submissionTable" (id uuid PRIMARY KEY, assignment_id uuid, classroom_id uuid, student_id uuid);
    INSERT INTO "userTable" (id,full_name,role) VALUES ('${t}','Teacher','teacher'),('${other}','Other','teacher'),('${s}','Alex Santos','student'),('${peer}','Peer','student'),('${outsider}','Outsider','student');
    INSERT INTO "classroomTable" VALUES ('${A}','${t}',true),('${B}','${other}',true);
    INSERT INTO "classroomMembers" VALUES ('${A}','${s}'),('${A}','${peer}'),('${B}','${outsider}');
    INSERT INTO "assignmentTable" VALUES ('${a}','${A}','${t}'),('${b}','${B}','${other}'),('${a2}','${A}','${t}');
    INSERT INTO "submissionTable" VALUES ('${work}','${a}','${A}','${s}');`);
  for (const [file,names] of [['admin_schema.sql',['writecheck_active','writecheck_admin']], ['submission_security.sql',['can_manage_classroom','can_use_assignment','can_access_submission']]]) {
    const source=fs.readFileSync(file,'utf8');
    for (const name of names) {const start=source.indexOf(`CREATE OR REPLACE FUNCTION public.${name}(`);const end=source.indexOf('$$;',source.indexOf('AS $$',start)); await db.exec(source.slice(start,end+3));}
  }
  await db.exec(`CREATE TABLE auth.users (id uuid PRIMARY KEY, email text, raw_user_meta_data jsonb DEFAULT '{}'::jsonb, created_at timestamptz DEFAULT now());
    ALTER TABLE "userTable" ADD COLUMN email text; ALTER TABLE "userTable" ADD COLUMN registered_at timestamptz;
    CREATE TABLE activity_logs (user_id uuid, actor_name text, actor_role text, action text, target_type text, target_id text, target_name text);
    GRANT SELECT, UPDATE ON "userTable" TO authenticated;
    ALTER TABLE "classroomTable" ENABLE ROW LEVEL SECURITY;
    GRANT SELECT ON "classroomTable" TO authenticated;
    CREATE POLICY visible ON "classroomTable" FOR SELECT TO authenticated USING(true);
    CREATE POLICY active_only ON "classroomTable" AS RESTRICTIVE FOR SELECT TO authenticated USING(public.writecheck_active());`);
  await db.exec(fs.readFileSync('assignment_comments.sql','utf8'));
  const as = async id => {await db.exec('RESET ROLE');await db.query("SELECT set_config('test.uid',$1,false)",[id]);await db.exec('SET ROLE authenticated');};
  const list = async (assignment=a, room=A) => (await db.query('SELECT public.list_assignment_comments($1,$2) AS rows',[assignment,room])).rows[0].rows;
  // Legacy comments migrate as private, never become visible to classmates.
  await as(s); await db.query('SELECT public.post_assignment_comment($1,$2,$3)',[a,A,'Legacy private']);
  await db.exec('RESET ROLE'); await db.exec(fs.readFileSync('comment_visibility.sql','utf8'));
  const post = (kind,text,recipient=null,assignment=a,room=A) => db.query('SELECT public.post_assignment_comment($1,$2,$3,$4,$5)',[assignment,room,text,kind,recipient]);
  await as(s); await post('class','Class question'); await post('private','Private question');
  await assert.rejects(post('private','Spoofed student',peer));
  await assert.rejects(post('class','Wrong classroom',null,a,B));
  await as(peer); assert.deepEqual((await list()).map(r=>r.comment_text),['Class question']);
  assert.deepEqual(await list(a2,A),[]);
  await as(t); assert.equal((await list()).length,3); await post('private','Teacher reply',s);
  await as(s); assert.equal((await list()).find(r=>r.comment_text==='Teacher reply').sender_id,t);
  await as(peer); assert.deepEqual((await list()).map(r=>r.comment_text),['Class question']);
  await as(other); await assert.rejects(list()); await assert.rejects(post('private','Intrusion',s));
  assert.deepEqual(await list(b,B),[]);
  await as(outsider); await assert.rejects(list());
  await db.exec('RESET ROLE');
  const admin='00000000-0000-0000-0000-000000000020';
  const fresh='00000000-0000-0000-0000-000000000021';
  const newTeacher='00000000-0000-0000-0000-000000000022';
  const bad='00000000-0000-0000-0000-000000000023';
  await db.query(`INSERT INTO "userTable"(id,full_name,role,account_status) VALUES ($1,'Admin','admin','active')`,[admin]);
  await db.exec(fs.readFileSync('registration_approval.sql','utf8'));
  await db.exec(`CREATE TRIGGER guard_profile_fields BEFORE INSERT OR UPDATE ON "userTable" FOR EACH ROW EXECUTE FUNCTION public.guard_profile_fields();`);
  await db.exec(fs.readFileSync('registration_edu_ph.sql','utf8'));
  const signup=(id,email,role='student')=>db.query('INSERT INTO auth.users(id,email,raw_user_meta_data) VALUES ($1,$2,$3)',[id,email,JSON.stringify({full_name:'New account',role,account_status:'active'})]);
  for(const email of ['x@gmail.com','x@sub.edu.com.ph','x@edu.com.ph.evil.com','x@edu.com.ph ','x@school.edu.ph.evil.com','x@fakeedu.ph','x@-school.edu.ph','x@school..edu.ph']) await assert.rejects(signup(bad,email));
  await signup(fresh,'New@EDU.COM.PH'); await signup(newTeacher,'teacher@edu.com.ph','teacher');
  for (const [i,email] of ['student@school.edu.ph','teacher@DEPT.SCHOOL.EDU.PH'].entries()) {
    const id = '00000000-0000-0000-0000-00000000003' + i;
    await signup(id,email,i ? 'teacher' : 'student');
    assert.equal((await db.query('SELECT account_status FROM "userTable" WHERE id=$1',[id])).rows[0].account_status,'pending');
  }
  let records=await db.query('SELECT account_status,role FROM "userTable" WHERE id=$1',[fresh]);
  assert.equal(records.rows[0].account_status,'pending');
  assert.equal((await db.query('SELECT account_status FROM "userTable" WHERE id=$1',[t])).rows[0].account_status,'active');
  await as(fresh);
  assert.equal((await db.query('SELECT * FROM "classroomTable"')).rows.length,0);
  await assert.rejects(db.query(`UPDATE "userTable" SET account_status='active' WHERE id=$1`,[fresh]));
  await assert.rejects(db.query('SELECT public.admin_set_account_status($1,$2)',[fresh,'active']));
  await assert.rejects(db.query('SELECT public.leave_classroom($1)',[A]));
  await as(newTeacher); await assert.rejects(db.query('SELECT public.archive_classroom($1,true)',[A]));
  await as(admin); await assert.rejects(db.query('SELECT public.admin_set_account_status($1,$2)',[admin,'active']));
  await db.query('SELECT public.admin_set_account_status($1,$2)',[fresh,'active']);
  await db.query('SELECT public.admin_set_account_status($1,$2)',[newTeacher,'rejected']);
  await as(fresh); assert.equal((await db.query('SELECT public.writecheck_active() AS ok')).rows[0].ok,true);
  await as(newTeacher); assert.equal((await db.query('SELECT public.writecheck_active() AS ok')).rows[0].ok,false);
  await assert.rejects(db.query('SELECT public.admin_set_account_status($1,$2)',[newTeacher,'active']));
  await as(admin); await db.query('SELECT public.admin_set_account_status($1,$2)',[newTeacher,'active']);
  await as(newTeacher); assert.equal((await db.query('SELECT public.writecheck_active() AS ok')).rows[0].ok,true);
  await db.exec('RESET ROLE');
  const orphan = '00000000-0000-0000-0000-000000000040';
  await db.exec('ALTER TABLE auth.users DISABLE TRIGGER zzzz_writecheck_pending_account');
  await signup(orphan, 'missing@school.edu.ph', 'teacher');
  await db.exec('ALTER TABLE auth.users ENABLE TRIGGER zzzz_writecheck_pending_account');
  await db.exec(fs.readFileSync('admin_registration_repair.sql', 'utf8'));
  await db.exec(fs.readFileSync('admin_registration_repair.sql', 'utf8'));
  assert.deepEqual((await db.query('SELECT role,account_status FROM "userTable" WHERE id=$1', [orphan])).rows,
    [{ role: 'teacher', account_status: 'pending' }]);
  assert.equal((await db.query('SELECT account_status FROM "userTable" WHERE id=$1', [fresh])).rows[0].account_status, 'active');
  const adminSource = fs.readFileSync('admin_schema.sql', 'utf8');
  const readStart = adminSource.indexOf('CREATE OR REPLACE FUNCTION public.admin_read(');
  const readEnd = adminSource.indexOf('$$;', adminSource.indexOf('AS $$', readStart));
  await db.exec(adminSource.slice(readStart, readEnd + 3));
  await as(admin);
  const pending = (await db.query("SELECT public.admin_read('users', '{\"status\":\"pending\"}'::jsonb) AS result")).rows[0].result;
  assert.ok(pending.items.some(row => row.id === orphan));
  assert.ok(pending.items.every(row => row.account_status === 'pending'));
  assert.ok(!pending.items.some(row => row.id === fresh));
  await as(peer); await assert.rejects(db.query("SELECT public.admin_read('users', '{}'::jsonb)"));
  await as(admin); await db.query('SELECT public.admin_set_account_status($1,$2)', [orphan, 'active']);
  await as(orphan); assert.equal((await db.query('SELECT public.writecheck_active() AS ok')).rows[0].ok, true);
  await db.close();
  console.log('PASS: class/private isolation, domain checks, pending signup, approval authorization, active-only access, missing-profile repair, pending admin listing, and preserved existing statuses.');
})().catch(error=>{console.error(error);process.exitCode=1;});
